/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practica04CarlosZuniga;

import java.util.Set;
import javax.swing.JOptionPane;
import jdk.internal.util.StaticProperty;

/**
 *
 * @author Usuario
 */
public class UI
        extends javax.swing.JFrame
{

   Equipo equipo[] = new Equipo[20];
    int i =0;
    /**
     * Creates new form UI
     */
    public UI()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jRegistrar = new javax.swing.JButton();
        JLimpiar = new javax.swing.JButton();
        jNjugador = new javax.swing.JTextField();
        jAjugador = new javax.swing.JTextField();
        jRegistro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jEstatura = new javax.swing.JTextField();
        jEliminar = new javax.swing.JButton();
        jBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Equipo Ceti");

        jRegistrar.setLabel("Registrar");
        jRegistrar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRegistrarActionPerformed(evt);
            }
        });

        JLimpiar.setLabel("Limpiar");
        JLimpiar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                JLimpiarActionPerformed(evt);
            }
        });

        jNjugador.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jNjugadorActionPerformed(evt);
            }
        });

        jAjugador.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jAjugadorActionPerformed(evt);
            }
        });

        jLabel2.setText("Ingresa el Nombre del jugador");

        jLabel3.setText("Ingresa el Apellido del Jugador");

        jLabel4.setText("Ingresa el Registro del jugador");

        jLabel5.setText("Ingresa la estatura del jugador");

        jEliminar.setLabel("Eliminar");
        jEliminar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jEliminarActionPerformed(evt);
            }
        });

        jBuscar.setText("Buscar");
        jBuscar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jRegistrar)
                .addGap(43, 43, 43)
                .addComponent(JLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jBuscar)
                .addGap(54, 54, 54)
                .addComponent(jEliminar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jEstatura, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNjugador, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAjugador, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 107, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(303, 303, 303))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jNjugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jAjugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jEstatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRegistrar)
                    .addComponent(JLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRegistrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRegistrarActionPerformed
    {//GEN-HEADEREND:event_jRegistrarActionPerformed


        equipo[i] = new Equipo();
        if(i >= equipo.length){
             JOptionPane.showMessageDialog(null,  "no puedes agregar mas datos", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
        equipo[i].setNombre(jNjugador.getText());
        equipo[i].setApellido(jAjugador.getText());
        equipo[i].setRegistro(Integer.parseInt(jRegistro.getText()));
        equipo[i].setEstatura(Integer.parseInt(jEstatura.getText()));
        i++;
        }

    }//GEN-LAST:event_jRegistrarActionPerformed

    private void jNjugadorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jNjugadorActionPerformed
    {//GEN-HEADEREND:event_jNjugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNjugadorActionPerformed

    private void jAjugadorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jAjugadorActionPerformed
    {//GEN-HEADEREND:event_jAjugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAjugadorActionPerformed

    private void JLimpiarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_JLimpiarActionPerformed
    {//GEN-HEADEREND:event_JLimpiarActionPerformed
        jAjugador.setText(null);
        jRegistro.setText(null);
        jNjugador.setText(null);
        jEstatura.setText(null);
    }//GEN-LAST:event_JLimpiarActionPerformed

    private void jEliminarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jEliminarActionPerformed
    {//GEN-HEADEREND:event_jEliminarActionPerformed
        for(int j=0; j>equipo.length -1; j++){
            if(equipo[j] !=null){
                if(Integer.parseInt(jRegistro.getText())==equipo[j].getRegistro()){
                    for(int k= j; k<equipo.length-1;k++){
                        if(equipo[k+1]==null){
                            equipo[k]=null;
                            break;
                        }
                    }

                }
            }
        }

    }//GEN-LAST:event_jEliminarActionPerformed

    private void jBuscarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBuscarActionPerformed
    {//GEN-HEADEREND:event_jBuscarActionPerformed

                 for(int k =0; k< equipo.length-1;k++){
                     if(equipo[k]== null && equipo[k+1]== null){
                         break;

                     }
                 else if(jNjugador.getText().equals(equipo[k].getNombre())){
                     jNjugador.setText(equipo[k].getNombre());
                     String s= Integer.toString(equipo[k].getRegistro());
                     jRegistro.setText(s);
                     s = Integer.toString(equipo[k].getEstatura());
                     jAjugador.setText(equipo[k].getApellido());
                     jEstatura.setText(s);
                     break;
                         }
                 }
        }//GEN-LAST:event_jBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.
                    getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(UI.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(UI.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(UI.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(UI.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JLimpiar;
    private javax.swing.JTextField jAjugador;
    private javax.swing.JButton jBuscar;
    private javax.swing.JButton jEliminar;
    private javax.swing.JTextField jEstatura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jNjugador;
    private javax.swing.JButton jRegistrar;
    private javax.swing.JTextField jRegistro;
    // End of variables declaration//GEN-END:variables
}
